# SwiftLint Configuration for Paint My Town
# Version: 1.0

# Paths to include/exclude
included:
  - PaintMyTown
  - PaintMyTownTests

excluded:
  - Pods
  - Carthage
  - .build
  - DerivedData
  - .swiftpm
  - PaintMyTown/Assets.xcassets
  - PaintMyTown/Preview Content

# Rule Configuration
disabled_rules:
  - trailing_whitespace # Allow trailing whitespace for now
  - todo # Allow TODO comments during development

opt_in_rules:
  - array_init
  - attributes
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_first_not_nil
  - empty_count
  - empty_string
  - explicit_init
  - extension_access_modifier
  - fallthrough
  - fatal_error_message
  - first_where
  - force_unwrapping # Warn about force unwrapping
  - implicitly_unwrapped_optional
  - joined_default_parameter
  - literal_expression_end_indentation
  - multiline_arguments
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - operator_usage_whitespace
  - overridden_super_call
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - redundant_nil_coalescing
  - redundant_type_annotation
  - sorted_first_last
  - toggle_bool
  - trailing_closure
  - unneeded_parentheses_in_closure_argument
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - yoda_condition

# Custom Rule Parameters
line_length:
  warning: 120
  error: 150
  ignores_comments: true
  ignores_urls: true

type_body_length:
  warning: 300
  error: 400

file_length:
  warning: 500
  error: 800
  ignore_comment_only_lines: true

function_body_length:
  warning: 50
  error: 100

function_parameter_count:
  warning: 5
  error: 8

cyclomatic_complexity:
  warning: 10
  error: 20
  ignores_case_statements: true

nesting:
  type_level:
    warning: 2
  statement_level:
    warning: 5

type_name:
  min_length:
    warning: 3
    error: 2
  max_length:
    warning: 50
    error: 60
  excluded:
    - ID
    - URL
    - GPS

identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 50
    error: 60
  excluded:
    - id
    - x
    - y
    - km
    - mi
    - db

# Force Cast
force_cast: warning
force_try: warning
force_unwrapping: warning

# Large Tuple
large_tuple:
  warning: 3
  error: 4

# Empty Count
empty_count: warning

# Attributes
attributes:
  always_on_same_line:
    - "@IBAction"
    - "@NSManaged"
    - "@objc"
  always_on_line_above:
    - "@Published"
    - "@State"
    - "@Binding"
    - "@ObservedObject"
    - "@EnvironmentObject"
    - "@Environment"
    - "@Injected"
    - "@InjectedOptional"

# Trailing Comma
trailing_comma:
  mandatory_comma: true

# Custom Rules
custom_rules:
  # Ensure proper MARK usage
  mark_format:
    name: "MARK Format"
    regex: '\/\/\s*MARK:\s*(?![A-Z])'
    message: "MARK comments should be followed by a space and start with a capital letter"
    severity: warning

  # Discourage print statements (use Logger instead)
  no_print:
    name: "No Print"
    regex: '\bprint\('
    match_kinds:
      - identifier
    message: "Use Logger instead of print() for logging"
    severity: warning

  # Ensure async functions are properly named
  async_naming:
    name: "Async Function Naming"
    regex: 'func\s+(?!.*async\b).*\basync\b.*\{'
    message: "Async functions should have 'async' in their name or use the async keyword"
    severity: warning

# Reporter
reporter: "xcode" # Use Xcode-compatible output format
